@Library('frontend-ci-checks') _

frontendCI(
    gitRepo: "https://github.com/OT-MICROSERVICES/frontend.git",
    gitBranch: "main",
    nodeTool: "node-16",
    sonarProject: "frontend-ci-checks",
    sonarName: "frontend-ci-checks"
)