@Library('license-scan-shared') _   
pipeline {
    agent any

    stages {
        stage('License Scanning') {
            steps {
                script {
                    licenseScanningGeneric(
                        
                        // added repo url in jenkinsfile
                        repoUrl: 'https://github.com/OT-MICROSERVICES/salary-api.git',
                        branch: 'main',
                        reportDir: 'reports',
                        slackChannel: '#ci-operation-notifications'
                    )
                }
            }
        }
    }
}